# Generated by Django 6.0.4 on 2026-04-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
