# Generated by Django 6.0.4 on 2026-04-19 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'content_chapter',
                'ordering': ['subject', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'content_exam_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'content_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('q_type', models.CharField(choices=[('MCQ_SINGLE', 'MCQ Single Correct'), ('MCQ_MULTI', 'MCQ Multiple Correct'), ('INTEGER', 'Integer / Numerical'), ('FILL_BLANK', 'Fill in the Blank'), ('SUBJECTIVE', 'Subjective')], default='MCQ_SINGLE', max_length=12)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=6)),
                ('text', models.TextField(help_text='Supports LaTeX via KaTeX. Use $...$ for inline math.')),
                ('image', models.ImageField(blank=True, upload_to='questions/images/')),
                ('solution', models.TextField(blank=True)),
                ('solution_video', models.URLField(blank=True)),
                ('marks_correct', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('marks_wrong', models.DecimalField(decimal_places=2, default=-1, max_digits=5)),
                ('marks_partial', models.DecimalField(decimal_places=2, default=0, help_text='Partial marks for MCQ_MULTI when some correct options are selected.', max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(blank=True, help_text='PYQ year if this is a previous year question.', null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.chapter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='content.tag')),
            ],
            options={
                'db_table': 'content_question',
                'ordering': ['chapter', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content.examtype')),
            ],
            options={
                'db_table': 'content_subject',
                'ordering': ['exam_type', 'order', 'name'],
                'unique_together': {('exam_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content.subject'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='questions/options/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.question')),
            ],
            options={
                'db_table': 'content_question_option',
                'ordering': ['question', 'order'],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'name')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter', 'difficulty'], name='content_que_chapter_a93b50_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['q_type', 'is_verified'], name='content_que_q_type_e7871f_idx'),
        ),
    ]
