# Generated by Django 6.0.4 on 2026-04-19 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('access_type', models.CharField(choices=[('OPEN', 'Open to all'), ('ASSIGNED', 'Assigned only'), ('BATCH', 'Batch')], default='OPEN', max_length=10)),
                ('start_time', models.DateTimeField(blank=True, help_text='Leave blank for always-open quiz.', null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_mins', models.PositiveIntegerField(help_text='Total exam duration in minutes.')),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('shuffle_options', models.BooleanField(default=False)),
                ('show_solution_after', models.CharField(choices=[('SUBMIT', 'After submit'), ('END_TIME', 'After end time'), ('NEVER', 'Never')], default='SUBMIT', max_length=10)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('pass_percentage', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('instructions', models.TextField(blank=True)),
                ('is_proctored', models.BooleanField(default=False, help_text='Enable tab-switch and fullscreen monitoring.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='content.examtype')),
            ],
            options={
                'db_table': 'quiz_quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration_mins', models.PositiveIntegerField(blank=True, help_text='Per-section timer. If null, uses the quiz-level timer.', null=True)),
                ('max_questions', models.PositiveIntegerField(blank=True, help_text='If set, students can only attempt this many questions in the section.', null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quiz.quiz')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sections', to='content.subject')),
            ],
            options={
                'db_table': 'quiz_section',
                'ordering': ['quiz', 'order'],
                'unique_together': {('quiz', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QuizAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_assignments', to='accounts.batch')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='quiz.quiz')),
            ],
            options={
                'db_table': 'quiz_assignment',
                'constraints': [models.CheckConstraint(condition=models.Q(('assigned_to__isnull', False), ('batch__isnull', False), _connector='OR'), name='assignment_has_target')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks_correct', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides Question.marks_correct if set.', max_digits=5, null=True)),
                ('marks_wrong', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides Question.marks_wrong if set.', max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='content.question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quizsection')),
            ],
            options={
                'db_table': 'quiz_question',
                'ordering': ['section', 'order'],
                'unique_together': {('section', 'question')},
            },
        ),
    ]
