# Generated by Django 6.0.4 on 2026-04-19 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('TIMED_OUT', 'Timed Out'), ('ABANDONED', 'Abandoned')], default='IN_PROGRESS', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('time_elapsed_secs', models.PositiveIntegerField(default=0, help_text='Updated via heartbeat every 30 seconds.')),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('correct_count', models.PositiveIntegerField(null=True)),
                ('wrong_count', models.PositiveIntegerField(null=True)),
                ('skipped_count', models.PositiveIntegerField(null=True)),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rank', models.PositiveIntegerField(null=True)),
                ('is_passed', models.BooleanField(null=True)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('fullscreen_exits', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempt_quiz_attempt',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'quiz', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_status', models.CharField(choices=[('NOT_VISITED', 'Not Visited'), ('VISITED', 'Visited / Seen'), ('ANSWERED', 'Answered'), ('MARKED_REVIEW', 'Marked for Review'), ('ANSWERED_REVIEW', 'Answered + Marked for Review')], default='NOT_VISITED', max_length=16)),
                ('integer_answer', models.DecimalField(blank=True, decimal_places=4, help_text='For INTEGER / FILL_BLANK question types.', max_digits=10, null=True)),
                ('text_answer', models.TextField(blank=True, help_text='For SUBJECTIVE question types.')),
                ('first_visited_at', models.DateTimeField(blank=True, null=True)),
                ('last_answered_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_secs', models.PositiveIntegerField(default=0, help_text='Cumulative seconds spent on this question.')),
                ('is_correct', models.BooleanField(null=True)),
                ('marks_awarded', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('is_manually_graded', models.BooleanField(default=False, help_text='True for SUBJECTIVE; graded by an admin.')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='quiz.quizquestion')),
                ('selected_options', models.ManyToManyField(blank=True, help_text='For MCQ_SINGLE and MCQ_MULTI.', to='content.questionoption')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='attempt.quizattempt')),
            ],
            options={
                'db_table': 'attempt_question_response',
                'unique_together': {('attempt', 'quiz_question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('VISIT', 'Question visited'), ('ANSWER', 'Answer selected/changed'), ('CLEAR', 'Answer cleared'), ('MARK_REVIEW', 'Marked for review'), ('UNMARK', 'Review unmarked'), ('LEAVE', 'Navigated away')], max_length=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_on_q_secs', models.PositiveIntegerField(help_text='Seconds spent on this question before this event fired.')),
                ('payload', models.JSONField(default=dict, help_text='Selected option ids, integer value, or other event data.')),
                ('quiz_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quiz.quizquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attempt.quizattempt')),
            ],
            options={
                'db_table': 'attempt_question_event',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['attempt', 'quiz_question', 'timestamp'], name='attempt_que_attempt_2787d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SectionTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('time_used_secs', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_timers', to='attempt.quizattempt')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='quiz.quizsection')),
            ],
            options={
                'db_table': 'attempt_section_timer',
                'unique_together': {('attempt', 'section')},
            },
        ),
    ]
