# Generated by Django 6.0.4 on 2026-04-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz', 'difficulty_level']},
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium-Easy'), (4, 'Medium'), (5, 'Medium-Hard'), (6, 'Hard'), (7, 'Very Hard'), (8, 'Extremely Hard'), (9, 'JEE Advanced Level'), (10, 'Expert Level')], default=5),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.subject'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'difficulty_level'], name='quizzes_que_subject_eaf23f_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter', 'difficulty_level'], name='quizzes_que_chapter_342aa8_idx'),
        ),
    ]
